data = {
	'Instructing_Agent': 'JSBLPKKA',
	'Instructed_Agent': 'HSBCPKKX',
	'Message_Reference': 'ADPSPKR103001',
	'Message_Creation_Timestamp': '2019-09-29T09:02:01+05:00',
	'Payment_Priority': '0020',
    'No_of_Settlement': 3,
    'Total_Settlement_Amount': 888,
	'Settlement_Date': '29/09/2019',
    'Settlements': [
        {
            'Message_Reference': 'ADPSPKR103001/1',
            'Transaction_Reference': 'ADPSPKR103001//ADPSPKR103001/1',
			'Settlement_Amount': 888,
			'Charges_bearer': 'SHAR',
			'Debtor_Agent': 'JSBLPKKA',
			'Debtor_Client': 'REAL ESTATE CONSTRUCTION LTD',
			'Debtor_Client_Account': '3734500000',	
			'Creditor_Agent': 'HSBCPKKX',
			'Creditor_Client': 'CLOUD SYSTEMS LTD',
			'Creditor_Client_Account': '3854300000',
        },
        {
            'Message_Reference': 'ADPSPKR103001/2',
            'Transaction_Reference': 'ADPSPKR103001//ADPSPKR103001/2',
			'Settlement_Amount': 888,
			'Charges_bearer': 'SHAR',
			'Debtor_Agent': 'JSBLPKKA',
			'Debtor_Client': 'REAL ESTATE CONSTRUCTION LTD',
			'Debtor_Client_Account': '3734500000',	
			'Creditor_Agent': 'HSBCPKKX',
			'Creditor_Client': 'CLOUD SYSTEMS LTD',
			'Creditor_Client_Account': '3854300000',
        },
        {
            'Message_Reference': 'ADPSPKR103001/3',
            'Transaction_Reference': 'ADPSPKR103001//ADPSPKR103001/3',
			'Settlement_Amount': 888,
			'Charges_bearer': 'SHAR',
			'Debtor_Agent': 'JSBLPKKA',
			'Debtor_Client': 'REAL ESTATE CONSTRUCTION LTD',
			'Debtor_Client_Account': '3734500000',	
			'Creditor_Agent': 'HSBCPKKX',
			'Creditor_Client': 'CLOUD SYSTEMS LTD',
			'Creditor_Client_Account': '3854300000',
        }
	],
}

# Instructing agent will always be a sender and a debitor i.e from 
# Instructed agent will always be a receiver and a creditor i.e to

message = f'''
<?xml version="1.0" encoding="UTF-8"?>
<DataPDU xmlns="urn:cma:stp:xsd:stp.1.0">
	<Body>
		<!-- Application header -->
		<AppHdr xmlns="urn:iso:std:iso:20022:tech:xsd:head.001.001.02">
			<!-- Message Sender -->
			<Fr>
				<FIId>
					<FinInstnId>
						<BICFI>{data['Instructing_Agent']}</BICFI>
					</FinInstnId>
				</FIId>
			</Fr>
			<!-- Message Receiver -->
			<To>
				<FIId>
					<FinInstnId>
						<BICFI>{data['Instructed_Agent']}</BICFI>
					</FinInstnId>
				</FIId>
			</To>
			<!-- Message Reference -->
			<BizMsgIdr>{data['Message_Reference']}</BizMsgIdr>
			<!-- Message Type -->
			<MsgDefIdr>pacs.008.001.08</MsgDefIdr>
			<!-- Business Service -->
			<BizSvc>sbp.rtgs.01</BizSvc>
			<!-- Message Creation Date/Time-->
			<CreDt>{data['Message_Creation_Timestamp']}</CreDt>
			<!--Payment priority -->
			<Prty>{data['Payment_Priority']}</Prty>
		</AppHdr>
		<!-- Document -->
		<Document xmlns="urn:iso:std:iso:20022:tech:xsd:pacs.008.001.08">
			<FIToFICstmrCdtTrf>
				<GrpHdr>
					<!--Unique message reference as generated by sending party.-->
					<MsgId>{data['Message_Reference']}</MsgId>
					<!-- Message creation date-time -->
					<CreDtTm>{data['Message_Creation_Timestamp']}</CreDtTm>
					<!-- <<true>> for MT102 equivalent -->
					<BtchBookg>true</BtchBookg>
					
                    <!-- Number of instructions inside the batch -->
					<NbOfTxs>{data['No_of_Settlement']}</NbOfTxs>
					<TtlIntrBkSttlmAmt Ccy="PKR">{data['Total_Settlement_Amount']}</TtlIntrBkSttlmAmt>
					<!--Requested payment settlement date -->
					<IntrBkSttlmDt>{data['Settlement_Date']}</IntrBkSttlmDt>
					
                    <!-- Fixed value CLRG -->
					<SttlmInf>
						<SttlmMtd>CLRG</SttlmMtd>
					</SttlmInf>
					<PmtTpInf>
					<!--Local instrument code identifying business process of the payment. -->
						<LclInstrm>
							<Prtry>RTGS-MCCT</Prtry>
						</LclInstrm>
					</PmtTpInf>
					
                    <!-- Instructing agent. Participant who is sending the payment to the system. BICFI for SWIFT-registered BIC.  
                    ClrSysMmbId/MmbId for pseudo-BIC code (non-SWIFT registered)-->
					<InstgAgt>
						<FinInstnId>
							<BICFI>{data['Instructing_Agent']}</BICFI>
						</FinInstnId>
					</InstgAgt>
					<!--Instructed agent. Participant who is receiving the payment. BICFI for SWIFT-registered BIC.  
                    ClrSysMmbId/MmbId for pseudo-BIC code (non-SWIFT registered)-->
					<InstdAgt>
						<FinInstnId>
							<BICFI>{data['Instructed_Agent']}</BICFI>
						</FinInstnId>
					</InstdAgt>
				</GrpHdr>
                
				<CdtTrfTxInf>
					<PmtId>
						<!-- Instruction identifier. Equivalent of field 21 in MT102 in this message version -->
						<InstrId>{data['Settlements'][0]['Message_Reference']}</InstrId>
						<!--End-to-End reference. Equivalent of field 70:/ROC/ in MT102 in this message version. NOTPROVIDED if there no such reference -->
						<EndToEndId>NOTPROVIDED</EndToEndId>
						<!--Unique transaction identifier. Concatenation of MsgId and InstrId -->
						<TxId>{data['Settlements'][0]['Transaction_Reference']}</TxId>
					</PmtId>
                    
					<!--Payment amount and currency code -->
					<IntrBkSttlmAmt Ccy="PKR">{data['Settlements'][0]['Settlement_Amount']}</IntrBkSttlmAmt>
					<!--Charges bearer indicatio. -->
					<ChrgBr>{data['Settlements'][0]['Charges_bearer']}</ChrgBr>
                    
                    <!--Debtor agent. In this message version: Participant to be debited in the RTGS suystem. 
					BICFI for SWIFT-registered participants. ClrSysMmbId/MmbId for pseudo-BIC code (non-SWIFT registered)
					Participant in Field 52 of MT102 -->
					<DbtrAgt>
						<FinInstnId>
							<BICFI>{data['Settlements'][0]['Debtor_Agent']}</BICFI>
						</FinInstnId>
					</DbtrAgt>
                    <!--Debtor client name -->
					<Dbtr>
						<Nm>{data['Settlements'][0]['Debtor_Client']}</Nm>
					</Dbtr>
					<!--Debtor client account -->
					<DbtrAcct>
						<Id>
							<Othr>
								<Id>{data['Settlements'][0]['Debtor_Client_Account']}</Id>
							</Othr>
						</Id>
					</DbtrAcct>
					
                    <!--Creditor agent. BICFI for SWIFT-registered participants. 
                    ClrSysMmbId/MmbId for pseudo-BIC code (non-SWIFT registered). Participant in Field 57 of MT102 -->
					<CdtrAgt>
						<FinInstnId>
							<BICFI>{data['Settlements'][0]['Creditor_Agent']}</BICFI>
						</FinInstnId>
					</CdtrAgt>
					<!--Creditor client name -->
                    <Cdtr>
						<Nm>{data['Settlements'][0]['Creditor_Client']}</Nm>
					</Cdtr>
					<!--Creditor client account -->
					<CdtrAcct>
						<Id>
							<Othr>
								<Id>{data['Settlements'][0]['Creditor_Client_Account']}</Id>
							</Othr>
						</Id>
					</CdtrAcct>
				</CdtTrfTxInf>
                
				<CdtTrfTxInf>
					<PmtId>
						<!-- Instruction identifier. Equivalent of field 21 in MT102 in this message version -->
						<InstrId>{data['Settlements'][1]['Message_Reference']}</InstrId>
						<!--End-to-End reference. Equivalent of field 70:/ROC/ in MT102 in this message version. NOTPROVIDED if there no such reference -->
						<EndToEndId>NOTPROVIDED</EndToEndId>
						<!--Unique transaction identifier. Concatenation of MsgId and InstrId -->
						<TxId>{data['Settlements'][1]['Transaction_Reference']}</TxId>
					</PmtId>
                    
					<!--Payment amount and currency code -->
					<IntrBkSttlmAmt Ccy="PKR">{data['Settlements'][1]['Settlement_Amount']}</IntrBkSttlmAmt>
					<!--Charges bearer indicatio. -->
					<ChrgBr>{data['Settlements'][1]['Charges_bearer']}</ChrgBr>
                    
                    <!--Debtor agent. In this message version: Participant to be debited in the RTGS suystem. 
					BICFI for SWIFT-registered participants. ClrSysMmbId/MmbId for pseudo-BIC code (non-SWIFT registered)
					Participant in Field 52 of MT102 -->
					<DbtrAgt>
						<FinInstnId>
							<BICFI>{data['Settlements'][1]['Debtor_Agent']}</BICFI>
						</FinInstnId>
					</DbtrAgt>
                    <!--Debtor client name -->
					<Dbtr>
						<Nm>{data['Settlements'][1]['Debtor_Client']}</Nm>
					</Dbtr>
					<!--Debtor client account -->
					<DbtrAcct>
						<Id>
							<Othr>
								<Id>{data['Settlements'][1]['Debtor_Client_Account']}</Id>
							</Othr>
						</Id>
					</DbtrAcct>
					
                    <!--Creditor agent. BICFI for SWIFT-registered participants. 
                    ClrSysMmbId/MmbId for pseudo-BIC code (non-SWIFT registered). Participant in Field 57 of MT102 -->
					<CdtrAgt>
						<FinInstnId>
							<BICFI>{data['Settlements'][1]['Creditor_Agent']}</BICFI>
						</FinInstnId>
					</CdtrAgt>
					<!--Creditor client name -->
                    <Cdtr>
						<Nm>{data['Settlements'][1]['Creditor_Client']}</Nm>
					</Cdtr>
					<!--Creditor client account -->
					<CdtrAcct>
						<Id>
							<Othr>
								<Id>{data['Settlements'][1]['Creditor_Client_Account']}</Id>
							</Othr>
						</Id>
					</CdtrAcct>
				</CdtTrfTxInf>
                
				<CdtTrfTxInf>
					<PmtId>
						<!-- Instruction identifier. Equivalent of field 21 in MT102 in this message version -->
						<InstrId>{data['Settlements'][2]['Message_Reference']}</InstrId>
						<!--End-to-End reference. Equivalent of field 70:/ROC/ in MT102 in this message version. NOTPROVIDED if there no such reference -->
						<EndToEndId>NOTPROVIDED</EndToEndId>
						<!--Unique transaction identifier. Concatenation of MsgId and InstrId -->
						<TxId>{data['Settlements'][2]['Transaction_Reference']}</TxId>
					</PmtId>
                    
					<!--Payment amount and currency code -->
					<IntrBkSttlmAmt Ccy="PKR">{data['Settlements'][2]['Settlement_Amount']}</IntrBkSttlmAmt>
					<!--Charges bearer indicatio. -->
					<ChrgBr>{data['Settlements'][2]['Charges_bearer']}</ChrgBr>
                    
                    <!--Debtor agent. In this message version: Participant to be debited in the RTGS suystem. 
					BICFI for SWIFT-registered participants. ClrSysMmbId/MmbId for pseudo-BIC code (non-SWIFT registered)
					Participant in Field 52 of MT102 -->
					<DbtrAgt>
						<FinInstnId>
							<BICFI>{data['Settlements'][2]['Debtor_Agent']}</BICFI>
						</FinInstnId>
					</DbtrAgt>
                    <!--Debtor client name -->
					<Dbtr>
						<Nm>{data['Settlements'][2]['Debtor_Client']}</Nm>
					</Dbtr>
					<!--Debtor client account -->
					<DbtrAcct>
						<Id>
							<Othr>
								<Id>{data['Settlements'][2]['Debtor_Client_Account']}</Id>
							</Othr>
						</Id>
					</DbtrAcct>
					
                    <!--Creditor agent. BICFI for SWIFT-registered participants. 
                    ClrSysMmbId/MmbId for pseudo-BIC code (non-SWIFT registered). Participant in Field 57 of MT102 -->
					<CdtrAgt>
						<FinInstnId>
							<BICFI>{data['Settlements'][2]['Creditor_Agent']}</BICFI>
						</FinInstnId>
					</CdtrAgt>
					<!--Creditor client name -->
                    <Cdtr>
						<Nm>{data['Settlements'][2]['Creditor_Client']}</Nm>
					</Cdtr>
					<!--Creditor client account -->
					<CdtrAcct>
						<Id>
							<Othr>
								<Id>{data['Settlements'][2]['Creditor_Client_Account']}</Id>
							</Othr>
						</Id>
					</CdtrAcct>
				</CdtTrfTxInf>
                
			</FIToFICstmrCdtTrf>
		</Document>
	</Body>
</DataPDU>
'''

draft_by_sbp = f'''
<?xml version="1.0" encoding="UTF-8"?>
<DataPDU xmlns="urn:cma:stp:xsd:stp.1.0">
	<Body>
		<!-- Application header -->
		<AppHdr xmlns="urn:iso:std:iso:20022:tech:xsd:head.001.001.02">
			<!-- Message Sender -->
			<Fr>
				<FIId>
					<FinInstnId>
						<BICFI>JSBLPKKA</BICFI>
					</FinInstnId>
				</FIId>
			</Fr>
			<!-- Message Receiver -->
			<To>
				<FIId>
					<FinInstnId>
						<BICFI>HSBCPKKX</BICFI>
					</FinInstnId>
				</FIId>
			</To>
			<!-- Message Reference -->
			<BizMsgIdr>213804</BizMsgIdr>
			<!-- Message Type -->
			<MsgDefIdr>pacs.008.001.08</MsgDefIdr>
			<!-- Business Service -->
			<BizSvc>sbp.rtgs.01</BizSvc>
			<!-- Message Creation Date/Time-->
			<CreDt>2019-09-29T19:02:00+05:00</CreDt>
			<!--Payment priority -->
			<Prty>0020</Prty>
		</AppHdr>
		<!-- Document -->
		<Document xmlns="urn:iso:std:iso:20022:tech:xsd:pacs.008.001.08">
			<FIToFICstmrCdtTrf>
				<GrpHdr>
					<!--Unique message reference as generated by sending party.-->
					<MsgId>213804</MsgId>
					<!-- Message creation date-time -->
					<CreDtTm>2019-09-29T19:02:00+05:00</CreDtTm>
					<!-- <<true>> for MT102 equivalent -->
					<BtchBookg>true</BtchBookg>
					<!-- Number of instructions inside the batch -->
					<NbOfTxs>3</NbOfTxs>
					<TtlIntrBkSttlmAmt Ccy="PKR">2300.</TtlIntrBkSttlmAmt>
					<!--Requested payment settlement date -->
					<IntrBkSttlmDt>2019-09-29</IntrBkSttlmDt>
					<!-- Fixed value CLRG -->
					<SttlmInf>
						<SttlmMtd>CLRG</SttlmMtd>
					</SttlmInf>
					<PmtTpInf>
					<!--Local instrument code identifying business process of the payment. -->
						<LclInstrm>
							<Prtry>RTGS-MCCT</Prtry>
						</LclInstrm>
					</PmtTpInf>
					<!-- Instructing agent. Participant who is sending the payment to the system. BICFI for SWIFT-registered BIC.  ClrSysMmbId/MmbId for pseudo-BIC code (non-SWIFT registered)-->
					<InstgAgt>
						<FinInstnId>
							<BICFI>JSBLPKKA</BICFI>
						</FinInstnId>
					</InstgAgt>
					<!--Instructed agent. Participant who is receiving the payment. BICFI for SWIFT-registered BIC.  ClrSysMmbId/MmbId for pseudo-BIC code (non-SWIFT registered)-->
					<InstdAgt>
						<FinInstnId>
							<BICFI>HSBCPKKX</BICFI>
						</FinInstnId>
					</InstdAgt>
				</GrpHdr>
				<CdtTrfTxInf>
					<PmtId>
<!-- Instruction identifier. Equivalent of field 21 in MT102 in this message version -->
						<InstrId>213804/001</InstrId>
						<!--End-to-End reference. Equivalent of field 70:/ROC/ in MT102 in this message version. NOTPROVIDED if there no such reference -->
						<EndToEndId>NOTPROVIDED</EndToEndId>
						<!--Unique transaction identifier. Concatenation of MsgId and InstrId -->
						<TxId>213804//213804/001</TxId>
					</PmtId>
					<!--Payment amount and currency code -->
					<IntrBkSttlmAmt Ccy="PKR">1000.</IntrBkSttlmAmt>
					<!--Charges bearer indicatio. -->
					<ChrgBr>SHAR</ChrgBr>
					<!--Debtor client information -->
					<Dbtr>
						<!--Debtor client name -->
						<Nm>Company A</Nm>
					</Dbtr>
					<!--Debtor client account -->
					<DbtrAcct>
						<Id>
							<Othr>
								<Id>123-456</Id>
							</Othr>
						</Id>
					</DbtrAcct>
<!--Debtor agent. In this message version: Participant to be debited in the RTGS suystem. 
BICFI for SWIFT-registered participants. ClrSysMmbId/MmbId for pseudo-BIC code (non-SWIFT registered)
Participant in Field 52 of MT102 -->
					<DbtrAgt>
						<FinInstnId>
							<BICFI>JSBLPKKA</BICFI>
						</FinInstnId>
					</DbtrAgt>
<!--Creditor agent. BICFI for SWIFT-registered participants. ClrSysMmbId/MmbId for pseudo-BIC code (non-SWIFT registered). Participant in Field 57 of MT102 -->
					<CdtrAgt>
						<FinInstnId>
							<BICFI>HSBCPKKX</BICFI>
						</FinInstnId>
					</CdtrAgt>
					<!--Creditor client information -->
					<Cdtr>
						<!--Creditor client name -->
						<Nm>Company B</Nm>
					</Cdtr>
					<!--Creditor client account -->
					<CdtrAcct>
						<Id>
							<Othr>
								<Id>456-123</Id>
							</Othr>
						</Id>
					</CdtrAcct>
					<!--Transaction type code as per defined in system dictionary of the codes -->
					<Purp>
						<Prtry>001</Prtry>
					</Purp>
					<!--Regulatory reporting information -->
					<RgltryRptg>
						<Dtls>
							<Inf>Regulatory 1</Inf>
						</Dtls>
					</RgltryRptg>
					<!--Remittance information -->
					<RmtInf>
						<Ustrd>Remit1</Ustrd>
					</RmtInf>
				</CdtTrfTxInf>
				<CdtTrfTxInf>
					<PmtId>
<!-- Instruction identifier. Equivalent of field 21 in MT102 in this message version -->
						<InstrId>213804/002</InstrId>
						<!--End-to-End reference. Equivalent of field 70:/ROC/ in MT102 in this message version. NOTPROVIDED if there no such reference -->
						<EndToEndId>NOTPROVIDED</EndToEndId>
				<!--Unique transaction identifier. Concantenation of MsgId and InstrId -->
						<TxId>213804//213804/002</TxId>
					</PmtId>
					<!--Payment amount and currency code -->
					<IntrBkSttlmAmt Ccy="PKR">1000.</IntrBkSttlmAmt>
					<!--Charges bearer indication. -->
					<ChrgBr>SHAR</ChrgBr>
					<!--Debtor client information -->
					<Dbtr>
						<!--Debtor client name -->
						<Nm>Company A</Nm>
						<!--Debtor client postal address -->
						<PstlAdr>
							<AdrLine>23 Green Trees str.</AdrLine>
						</PstlAdr>
					</Dbtr>
					<!--Debtor client account -->
					<DbtrAcct>
						<Id>
							<Othr>
								<Id>123-456</Id>
							</Othr>
						</Id>
					</DbtrAcct>
					<!--Debtor agent. BICFI for SWIFT-registered participants. ClrSysMmbId/MmbId for pseudo-BIC code (non-SWIFT registered). Participant in Field 52 of MT102 -->
					<DbtrAgt>
						<FinInstnId>
							<BICFI>JSBLPKKA</BICFI>
						</FinInstnId>
					</DbtrAgt>
<!--Creditor agent. BICFI for SWIFT-registered participants. ClrSysMmbId/MmbId for pseudo-BIC code (non-SWIFT registered). Participant in Field 57 of MT102 -->
					<CdtrAgt>
						<FinInstnId>
							<BICFI>HSBCPKKX</BICFI>
						</FinInstnId>
					</CdtrAgt>
					<!--Creditor client information -->
					<Cdtr>
						<!--Creditor client name -->
						<Nm>Company C</Nm>
					</Cdtr>
					<!--Creditor client account -->
					<CdtrAcct>
						<Id>
							<Othr>
								<Id>789-123</Id>
							</Othr>
						</Id>
					</CdtrAcct>
					<!--Transaction type code as per defined in system dictionary of the codes -->
					<Purp>
						<Prtry>001</Prtry>
					</Purp>
					<!--Regulatory reporting information -->
					<RgltryRptg>
						<Dtls>
							<Inf>Regulatory 2</Inf>
						</Dtls>
					</RgltryRptg>
					<!--Remittance information -->
					<RmtInf>
						<Ustrd>Remit2</Ustrd>
					</RmtInf>
				</CdtTrfTxInf>
				<CdtTrfTxInf>
					<PmtId>
<!-- Instruction identifier. Equivalent of field 21 in MT102 in this message version -->
						<InstrId>213804/003</InstrId>
						<!--End-to-End reference. Equivalent of field 70:/ROC/ in MT102 in this message version. NOTPROVIDED if there no such reference -->
						<EndToEndId>NOTPROVIDED</EndToEndId>
			<!--Unique transaction identifier. Concantenation of MsgId and InstrId -->
						<TxId>213804//213804/003</TxId>
					</PmtId>
					<!--Payment amount and currency code -->
					<IntrBkSttlmAmt Ccy="PKR">300</IntrBkSttlmAmt>
					<!-- Charges bearer indication -->
					<ChrgBr>SHAR</ChrgBr>
					<!--Debtor client information -->
					<Dbtr>
						<!--Debtor client name -->
						<Nm>Company D</Nm>
					</Dbtr>
					<!--Debtor client account -->
					<DbtrAcct>
						<Id>
							<Othr>
								<Id>123-789</Id>
							</Othr>
						</Id>
					</DbtrAcct>
					<!--Debtor agent. BICFI for SWIFT-registered participants. 
ClrSysMmbId/MmbId for pseudo-BIC code (non-SWIFT registered). Participant in Field 52 of MT102 -->
					<DbtrAgt>
						<FinInstnId>
							<BICFI>JSBLPKKA</BICFI>
						</FinInstnId>
					</DbtrAgt>
					<!--Creditor agent. BICFI for SWIFT-registered participants. 
ClrSysMmbId/MmbId for pseudo-BIC code (non-SWIFT registered). Participant in Field 57 of MT102 -->
					<CdtrAgt>
						<FinInstnId>
							<BICFI>HSBCPKKX</BICFI>
						</FinInstnId>
					</CdtrAgt>
					<!--Creditor client information -->
					<Cdtr>
						<!--Creditor client name -->
						<Nm>Company B</Nm>
						<!--Creditor client postal address -->
					</Cdtr>
					<!--Creditor client account -->
					<CdtrAcct>
						<Id>
							<Othr>
								<Id>7456-123</Id>
							</Othr>
						</Id>
					</CdtrAcct>
					<!--Transaction type code as per defined in system dictionary of the codes -->
					<Purp>
						<Prtry>001</Prtry>
					</Purp>
					<!--Regulatory reporting information -->
					<RgltryRptg>
						<Dtls>
							<Inf>Regulatory 3</Inf>
						</Dtls>
					</RgltryRptg>
					<!--Remittance information -->
					<RmtInf>
						<Ustrd>Remit3</Ustrd>
					</RmtInf>
				</CdtTrfTxInf>
			</FIToFICstmrCdtTrf>
		</Document>
	</Body>
</DataPDU>
'''