sample_data = {
	'Instructing_Agent': 'JSBLPKKA',
	'Instructed_Agent': 'HSBCPKKX',
	'Message_Reference': 'ADPSPKR103001',
	'Message_Creation_Timestamp': '2019-09-29T09:02:01+05:00',
	'Payment_Priority': '0020',
	'Transaction_Reference': '4e7b08db-68e1-4af3-ac40-cd06623bac8a',
	'Settlement_Amount': 888,
	'Settlement_Date': '29/09/2019',
	'Charges_bearer': 'SHAR',
    'Debtor_Agent': 'JSBLPKKA',
	'Debtor_Client': 'REAL ESTATE CONSTRUCTION LTD',
	'Debtor_Client_Account': '3734500000',	
	'Creditor_Agent': 'HSBCPKKX',
	'Creditor_Client': 'CLOUD SYSTEMS LTD',
	'Creditor_Client_Account': '3854300000',
}

# Instructing agent will always be a sender and a debitor i.e from 
# Instructed agent will always be a receiver and a creditor i.e to

def get_document(data):
	document = f'''
		<!-- Document -->
		<Document xmlns="urn:iso:std:iso:20022:tech:xsd:pacs.008.001.08">
			<FIToFICstmrCdtTrf>
				<GrpHdr>
					<!--Unique message reference as generated by sending party -->
					<MsgId>{data['Message_Reference']}</MsgId>
					<!-- Message creation date-time -->
					<CreDtTm>{data['Message_Creation_Timestamp']}</CreDtTm>
					<!-- Fixed value <<1>> for MT103 equivalent -->
					<NbOfTxs>1</NbOfTxs>
					<!-- Fixed value CLRG -->
					<SttlmInf>
						<SttlmMtd>CLRG</SttlmMtd>
					</SttlmInf>
				</GrpHdr>
				<CdtTrfTxInf>
					<PmtId>
						<!--Instruction reference. The same as MsgId and BizMsgIdr-->
						<InstrId>{data['Message_Reference']}</InstrId>
						<!--End-to-End reference. Equivalent of field 70:/ROC/ in MT103 in this message version. NOTPROVIDED if there no such reference -->
						<EndToEndId>NOTPROVIDED</EndToEndId>
						<!-- Unique transaction reference as generated by sending party. The same as MsgId in this message version -->
						<TxId>{data['Message_Reference']}</TxId>
						<!-- UETR-->
						<UETR>{data['Transaction_Reference']}</UETR>
					</PmtId>
					<PmtTpInf>
						<!--Local instrument code identifying business process of the payment. Fixed value -->
						<LclInstrm>
							<Prtry>RTGS-SCCT</Prtry>
						</LclInstrm>
					</PmtTpInf>
					
					<!--Payment amount and currency code -->
					<IntrBkSttlmAmt Ccy="PKR">{data['Settlement_Amount']}</IntrBkSttlmAmt>
					<!--Requested payment settlement date -->
					<IntrBkSttlmDt>{data['Settlement_Date']}</IntrBkSttlmDt>
					<!--Charges bearer indication. -->
					<ChrgBr>{data['Charges_bearer']}</ChrgBr>
					
					<!--Instructing agent. DP who is sending the payment and debited in PRISM. BICFI for SWIFT-registered BIC. 
					ClrSysMmbId/MmbId for pseudo-BIC code (non-SWIFT registered)-->
					<InstgAgt>
						<FinInstnId>
							<BICFI>{data['Instructing_Agent']}</BICFI>
						</FinInstnId>
					</InstgAgt>
					<!--Instructed agent. DP who is receiving the payment and credited in PRISM. BICFI for SWIFT-registered BIC. 
					ClrSysMmbId/MmbId for pseudo-BIC code (non-SWIFT registered)-->
					<InstdAgt>
						<FinInstnId>
							<BICFI>{data['Instructed_Agent']}</BICFI>
						</FinInstnId>
					</InstdAgt>
					
					<!--Debtor agent: Participant in Field 53a of MT103-->
					<DbtrAgt>
						<FinInstnId>
							<BICFI>{data['Debtor_Agent']}</BICFI>
						</FinInstnId>
					</DbtrAgt>
					<!--Debtor client information -->
					<Dbtr>
						<!--Debtor client name -->
						<Nm>{data['Debtor_Client']}</Nm>
					</Dbtr>
					<!--Debtor client account in Field 50 of MT103 -->
					<DbtrAcct>
						<Id>
							<Othr>
								<Id>{data['Debtor_Client_Account']}</Id>
							</Othr>
						</Id>
					</DbtrAcct>
					
					<!--Creditor agent. Participant in Field 57a of MT103
					BICFI for SWIFT-registered participants. ClrSysMmbId/MmbId for pseudo-BIC code (non-SWIFT registered) -->
					<CdtrAgt>
						<FinInstnId>
							<BICFI>{data['Creditor_Agent']}</BICFI>
						</FinInstnId>
					</CdtrAgt>
					<!--Creditor client information -->
					<Cdtr>
						<!--Creditor client name -->
						<Nm>{data['Creditor_Client']}</Nm>
					</Cdtr>
					<!--Creditor client account -->
					<CdtrAcct>
						<Id>
							<Othr>
								<Id>{data['Creditor_Client_Account']}</Id>
							</Othr>
						</Id>
					</CdtrAcct>
					
				</CdtTrfTxInf>
			</FIToFICstmrCdtTrf>
		</Document>
		'''
	return document

message = f'''
<?xml version="1.0" encoding="UTF-8"?>
<DataPDU xmlns="urn:cma:stp:xsd:stp.1.0">
	<Body>
		<!-- Application header -->
		<AppHdr xmlns="urn:iso:std:iso:20022:tech:xsd:head.001.001.02">
			<!-- Message Sender: -->
			<Fr>
				<FIId>
					<FinInstnId>
						<BICFI>{sample_data['Instructing_Agent']}</BICFI>
					</FinInstnId>
				</FIId>
			</Fr>
			<!-- Message Receiver -->
			<To>
				<FIId>
					<FinInstnId>
						<BICFI>{sample_data['Instructed_Agent']}</BICFI>
					</FinInstnId>
				</FIId>
			</To>
			<!-- Message Reference -->
			<BizMsgIdr>{sample_data['Message_Reference']}</BizMsgIdr>
			<!-- Message Type -->
			<MsgDefIdr>pacs.008.001.08</MsgDefIdr>
			<!-- Business Service -->
			<BizSvc>sbp.rtgs.01</BizSvc>
			<!-- Message Creation Date/Time-->
			<CreDt>{sample_data['Message_Creation_Timestamp']}</CreDt>
			<!--Payment priority-->
			<Prty>{sample_data['Payment_Priority']}</Prty>
		</AppHdr>
		<!-- Document -->
		<Document xmlns="urn:iso:std:iso:20022:tech:xsd:pacs.008.001.08">
			<FIToFICstmrCdtTrf>
				<GrpHdr>
					<!--Unique message reference as generated by sending party -->
					<MsgId>{sample_data['Message_Reference']}</MsgId>
					<!-- Message creation date-time -->
					<CreDtTm>{sample_data['Message_Creation_Timestamp']}</CreDtTm>
					<!-- Fixed value <<1>> for MT103 equivalent -->
					<NbOfTxs>1</NbOfTxs>
					<!-- Fixed value CLRG -->
					<SttlmInf>
						<SttlmMtd>CLRG</SttlmMtd>
					</SttlmInf>
				</GrpHdr>
				<CdtTrfTxInf>
					<PmtId>
						<!--Instruction reference. The same as MsgId and BizMsgIdr-->
						<InstrId>{sample_data['Message_Reference']}</InstrId>
						<!--End-to-End reference. Equivalent of field 70:/ROC/ in MT103 in this message version. NOTPROVIDED if there no such reference -->
						<EndToEndId>NOTPROVIDED</EndToEndId>
                        <!-- Unique transaction reference as generated by sending party. The same as MsgId in this message version -->
						<TxId>{sample_data['Message_Reference']}</TxId>
						<!-- UETR-->
						<UETR>{sample_data['Transaction_Reference']}</UETR>
					</PmtId>
					<PmtTpInf>
                        <!--Local instrument code identifying business process of the payment. Fixed value -->
						<LclInstrm>
							<Prtry>RTGS-SCCT</Prtry>
						</LclInstrm>
					</PmtTpInf>
					
                    <!--Payment amount and currency code -->
					<IntrBkSttlmAmt Ccy="PKR">{sample_data['Settlement_Amount']}</IntrBkSttlmAmt>
					<!--Requested payment settlement date -->
					<IntrBkSttlmDt>{sample_data['Settlement_Date']}</IntrBkSttlmDt>
					<!--Charges bearer indication. -->
					<ChrgBr>{sample_data['Charges_bearer']}</ChrgBr>
                    
					<!--Instructing agent. DP who is sending the payment and debited in PRISM. BICFI for SWIFT-registered BIC. 
                    ClrSysMmbId/MmbId for pseudo-BIC code (non-SWIFT registered)-->
					<InstgAgt>
						<FinInstnId>
							<BICFI>{sample_data['Instructing_Agent']}</BICFI>
						</FinInstnId>
					</InstgAgt>
                    <!--Instructed agent. DP who is receiving the payment and credited in PRISM. BICFI for SWIFT-registered BIC. 
                    ClrSysMmbId/MmbId for pseudo-BIC code (non-SWIFT registered)-->
					<InstdAgt>
						<FinInstnId>
							<BICFI>{sample_data['Instructed_Agent']}</BICFI>
						</FinInstnId>
					</InstdAgt>
					
					<!--Debtor agent: Participant in Field 53a of MT103-->
					<DbtrAgt>
						<FinInstnId>
							<BICFI>{sample_data['Debtor_Agent']}</BICFI>
						</FinInstnId>
					</DbtrAgt>
					<!--Debtor client information -->
					<Dbtr>
						<!--Debtor client name -->
						<Nm>{sample_data['Debtor_Client']}</Nm>
					</Dbtr>
					<!--Debtor client account in Field 50 of MT103 -->
					<DbtrAcct>
						<Id>
							<Othr>
								<Id>{sample_data['Debtor_Client_Account']}</Id>
							</Othr>
						</Id>
					</DbtrAcct>
					
					<!--Creditor agent. Participant in Field 57a of MT103
                    BICFI for SWIFT-registered participants. ClrSysMmbId/MmbId for pseudo-BIC code (non-SWIFT registered) -->
					<CdtrAgt>
						<FinInstnId>
							<BICFI>{sample_data['Creditor_Agent']}</BICFI>
						</FinInstnId>
					</CdtrAgt>
					<!--Creditor client information -->
					<Cdtr>
						<!--Creditor client name -->
						<Nm>{sample_data['Creditor_Client']}</Nm>
					</Cdtr>
					<!--Creditor client account -->
					<CdtrAcct>
						<Id>
							<Othr>
								<Id>{sample_data['Creditor_Client_Account']}</Id>
							</Othr>
						</Id>
					</CdtrAcct>
                    
				</CdtTrfTxInf>
			</FIToFICstmrCdtTrf>
		</Document>
	</Body>
</DataPDU>
'''

draft_by_sbp = f'''
<?xml version="1.0" encoding="UTF-8"?>
<DataPDU xmlns="urn:cma:stp:xsd:stp.1.0">
	<Body>
		<!-- Application header -->
		<AppHdr xmlns="urn:iso:std:iso:20022:tech:xsd:head.001.001.02">
			<!-- Message Sender: -->
			<Fr>
				<FIId>
					<FinInstnId>
						<BICFI>{'JSBLPKKA'}</BICFI>
					</FinInstnId>
				</FIId>
			</Fr>
			<!-- Message Receiver -->
			<To>
				<FIId>
					<FinInstnId>
						<BICFI>{'HSBCPKKX'}</BICFI>
					</FinInstnId>
				</FIId>
			</To>
			<!-- Message Reference -->
			<BizMsgIdr>{'ADPSPKR103001'}</BizMsgIdr>
			<!-- Message Type -->
			<MsgDefIdr>pacs.008.001.08</MsgDefIdr>
			<!-- Business Service -->
			<BizSvc>sbp.rtgs.01</BizSvc>
			<!-- Message Creation Date/Time-->
			<CreDt>{'2019-09-29T09:02:01+05:00'}</CreDt>
			<!--Payment priority-->
			<Prty>{'0020'}</Prty>
		</AppHdr>
		<!-- Document -->
		<Document xmlns="urn:iso:std:iso:20022:tech:xsd:pacs.008.001.08">
			<FIToFICstmrCdtTrf>
				<GrpHdr>
					<!--Unique message reference as generated by sending party -->
					<MsgId>{'ADPSPKR103001'}</MsgId>
					<!-- Message creation date-time -->
					<CreDtTm>{'2019-09-29T09:02:00+05:00'}</CreDtTm>
					<!-- Fixed value <<1>> for MT103 equivalent -->
					<NbOfTxs>1</NbOfTxs>
					<!-- Fixed value CLRG -->
					<SttlmInf>
						<SttlmMtd>CLRG</SttlmMtd>
					</SttlmInf>
				</GrpHdr>
				<CdtTrfTxInf>
					<PmtId>
						<!--Instruction reference. The same as MsgId and BizMsgIdr-->
						<InstrId>{'ADPSPKR103001'}</InstrId>
						<!--End-to-End reference. Equivalent of field 70:/ROC/ in MT103 in this message version. NOTPROVIDED if there no such reference -->
						<EndToEndId>NOTPROVIDED</EndToEndId>
                        <!-- Unique transaction reference as generated by sending party. The same as MsgId in this message version -->
						<TxId>{'ADPSPKR103001'}</TxId>
						<!-- UETR-->
						<UETR>{'4e7b08db-68e1-4af3-ac40-cd06623bac8a'}</UETR>
					</PmtId>
					<PmtTpInf>
                        <!--Local instrument code identifying business process of the payment. Fixed value -->
						<LclInstrm>
							<Prtry>RTGS-SCCT</Prtry>
						</LclInstrm>
					</PmtTpInf>
					<!--Payment amount and currency code -->
					<IntrBkSttlmAmt Ccy="PKR">{888.}</IntrBkSttlmAmt>
					<!--Requested payment settlement date -->
					<IntrBkSttlmDt>{'2019-09-29'}</IntrBkSttlmDt>
					<!--Charges bearer indication. -->
					<ChrgBr>{'SHAR'}</ChrgBr>
                    <!--Instructing agent. DP who is sending the payment and debited in PRISM. BICFI for SWIFT-registered BIC. 
                    ClrSysMmbId/MmbId for pseudo-BIC code (non-SWIFT registered)-->
					<InstgAgt>
						<FinInstnId>
							<BICFI>{'JSBLPKKA'}</BICFI>
						</FinInstnId>
					</InstgAgt>
                    <!--Instructed agent. DP who is receiving the payment and credited in PRISM. BICFI for SWIFT-registered BIC. 
                    ClrSysMmbId/MmbId for pseudo-BIC code (non-SWIFT registered)-->
					<InstdAgt>
						<FinInstnId>
							<BICFI>{'HSBCPKKX'}</BICFI>
						</FinInstnId>
					</InstdAgt>
                    
					<!--Debtor agent: Participant in Field 53a of MT103-->
					<DbtrAgt>
						<FinInstnId>
							<BICFI>{'JSBLPKKA'}</BICFI>
						</FinInstnId>
					</DbtrAgt>
					<!--Debtor client information -->
					<Dbtr>
						<!--Debtor client name -->
						<Nm>{'REAL ESTATE CONSTRUCTION LTD'}</Nm>
						<!--Debtor client postal address -->
						<PstlAdr>
							<AdrLine>{'15 Central street'}</AdrLine>
						</PstlAdr>
					</Dbtr>
					<!--Debtor client account in Field 50 of MT103 -->
					<DbtrAcct>
						<Id>
							<Othr>
								<Id>{'3734500000'}</Id>
							</Othr>
						</Id>
					</DbtrAcct>
                    
					<!--Creditor agent. Participant in Field 57a of MT103
                    BICFI for SWIFT-registered participants. ClrSysMmbId/MmbId for pseudo-BIC code (non-SWIFT registered) -->
					<CdtrAgt>
						<FinInstnId>
							<BICFI>{'HSBCPKKX'}</BICFI>
						</FinInstnId>
					</CdtrAgt>
					<!--Creditor client information -->
					<Cdtr>
						<!--Creditor client name -->
						<Nm>{'CLOUD SYSTEMS LTD'}</Nm>
						<!--Creditor client postal address -->
						<PstlAdr>
							<AdrLine>{'12 Green Trees str.'}</AdrLine>
							<AdrLine>{'City D'}</AdrLine>
						</PstlAdr>
					</Cdtr>
					<!--Creditor client account -->
					<CdtrAcct>
						<Id>
							<Othr>
								<Id>{'3854300000'}</Id>
							</Othr>
						</Id>
					</CdtrAcct>
					
                    <!--Additional information about payment. Equivalent of Field 72 in MT103 -->
					<InstrForNxtAgt>
						<InstrInf>/BNF/Test</InstrInf>
					</InstrForNxtAgt>
					<InstrForNxtAgt>
						<InstrInf>//Continuation</InstrInf>
					</InstrForNxtAgt>
					
                    <!--Transaction type code as per defined in system dictionary of the codes -->
					<Purp>
						<Prtry>001</Prtry>
					</Purp>
					
                    <!--Regulatory reporting -->
					<RgltryRptg>
						<Dtls>
							<Inf>PERIEWRJIWEK</Inf>
						</Dtls>
					</RgltryRptg>
					
                    <!--Remittance information -->
					<RmtInf>
						<Ustrd>/INV/52</Ustrd>
					</RmtInf>
                    
				</CdtTrfTxInf>
			</FIToFICstmrCdtTrf>
		</Document>
	</Body>
</DataPDU>
'''